spring:
#  elasticsearch:
#    jest:
#      uris: http://127.0.0.1:9200
  application:
    name: elasticSearchDemo
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
server:
  port: 8090
